CREATE TABLE IF NOT EXISTS ##DATABASE##.users
(
  id                            INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  email_address 				VARCHAR(255) NOT NULL,
  password_hash 				VARCHAR(300) NOT NULL,
  user_id 						CHAR(36) NOT NULL,
  is_first_time 				TINYINT(1) NOT NULL,
  is_inactive 					TINYINT(1) NOT NULL,
  is_suspended 					TINYINT(1) NOT NULL,
  is_reset_required 			TINYINT(1) NOT NULL,
  is_account_being_reset 		TINYINT(1) NOT NULL,
  is_profile_complete 			TINYINT(1) NOT NULL,
  title 						VARCHAR(10) DEFAULT NULL,
  first_name 					VARCHAR(50) DEFAULT NULL,
  last_name 					VARCHAR(50)  DEFAULT NULL,
  agency_name 					VARCHAR(100) DEFAULT NULL,
  is_full_name_set 				TINYINT(1) NOT NULL,
  phone_number 					VARCHAR(20) DEFAULT NULL,
  is_phone_number_set 			TINYINT(1) NOT NULL,
  post_code 					VARCHAR(10) DEFAULT NULL,
  address 						VARCHAR(100) DEFAULT NULL,
  city 							VARCHAR(20) DEFAULT NULL,
  country 						VARCHAR(40) DEFAULT NULL,
  logo_url 						VARCHAR(100) DEFAULT NULL,
  login_type 					VARCHAR(10) DEFAULT NULL,
  date_created 					DATETIME(6) NOT NULL,
  refresh_token                 VARCHAR(100) DEFAULT NULL,
  INDEX `index_user_email_address` (`email_address`),
  INDEX `index_user_user_id` (`user_id`),
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_general_ci;